---                                                  │
- hosts: all                                         │
  become: true                                       │
  tasks:                                             │
  - name: copy over SSH                              │
    ansible.builtin.copy:                            │
      src: index6.html                                      │
      dest: /var/www/html
