---
  - hosts: all
    become: true
    tasks:
    - name: Update Packages
      ansible.builtin.apt:
        update_cache: true
    - name: INSTALLATION OF Packages
      ansible.builtin.apt:
        name:
          - htop
          - git
          - vim-nox
